name: 'Frontend Check'
description: 'Runs lint, test, and build for the frontend'
outputs:
  status:
    description: 'The result of the frontend check'
    value: ${{ steps.summary.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: ðŸ“¦ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: frontend/pnpm-lock.yaml

    - name: ðŸ“¦ Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: ðŸ“¦ Install dependencies
      working-directory: frontend
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: ðŸ” Lint frontend code
      working-directory: frontend
      run: pnpm lint
      shell: bash

    - name: ðŸ§ª Run frontend tests
      working-directory: frontend
      run: pnpm test:coverage
      shell: bash

    - name: ðŸ—ï¸ Build frontend
      working-directory: frontend
      run: pnpm build
      shell: bash

    - name: ðŸ“ Set output status
      id: summary
      if: always()
      run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
      shell: bash