version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'chore(deps):'
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "
    groups:
      kotlin-stack:
        patterns:
          - "org.jetbrains.kotlin"           # Kotlin libraries
          - "com.google.devtools.ksp"        # Kotlin KSP
