{
 "title": "An-Na7wi",
 "description": "Main monitoring Dashboard for An-Na7wi",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard for آلنحوي  \n\nA simple Graphana Dashboard for the An-Na7wi application\n\nFor the moment it offers graphs for the following areas:\n\n- API Requests\n- Backend & JVM\n- Database"
   }
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests per 5min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/metrics\"}[5m])",
     "legendFormat": "{{ method }} {{ uri }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Successfull Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"2..\", instance=\"backend:8080\", uri!=\"/metrics\"}[1m])",
     "legendFormat": "{{ uri }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"4..\", instance=\"backend:8080\", uri!=\"/metrics\"}[1m])",
     "legendFormat": "{{ uri }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Server Error Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"5..\", instance=\"backend:8080\", uri!=\"/metrics\"}[1m])",
     "legendFormat": "{{ uri }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg by(uri) (rate(http_server_requests_seconds_max{uri!=\"/metrics\"}[5m]))",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "JVM Memory Max (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "GC Pause time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum",
     "legendFormat": "{{ gc }} action: {{ action }} - cause: {{ cause }}"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Up",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{job=\"postgres\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit per second",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=\"annahwi\"}[5m])"
      }
     ]
    },
    {
     "title": "Db Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "avg_over_time(pg_stat_activity_count{job=\"postgres\", datname=\"annahwi\", state=\"active\"}[5m])",
       "legendFormat": "state : {{ state }} -  event: {{ wait_event }} - type: {{ wait_event_type}}"
      }
     ]
    },
    {
     "title": "Sequential and Index Scans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_seq_scan{datname=\"annahwi\"}[1m])",
       "legendFormat": "SEQ_{{ relname }}"
      },
      {
       "expr": "rate(pg_stat_user_tables_idx_scan{datname=\"annahwi\"}[1m])",
       "legendFormat": "IDX_{{relname}}"
      }
     ]
    },
    {
     "title": "Size of Database",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{datname=\"annahwi\"} ",
       "legendFormat": "{{datname}} - {{__value__ | humanizeBinary}}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "pg_locks_count{datname=\"annahwi\"}",
       "legendFormat": "{{ mode }}"
      }
     ]
    }
   ]
  }
 ]
}