// Application enums
export enum Difficulty {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum Dialect {
  TUNISIAN = 'TUNISIAN',
  MOROCCAN = 'MOROCCAN',
  EGYPTIAN = 'EGYPTIAN',
  MSA = 'MSA',
  GULF = 'GULF',
  LEVANTINE = 'LEVANTINE',
  IRAQI = 'IRAQI',
}

export enum PartOfSpeech {
  UNKNOWN = 'UNKNOWN',
  NOUN = 'NOUN',
  VERB = 'VERB',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PREPOSITION = 'PREPOSITION',
  PARTICLE = 'PARTICLE',
  INTERJECTION = 'INTERJECTION',
  CONJUNCTION = 'CONJUNCTION',
  PRONOUN = 'PRONOUN',
}

export enum AnnotationType {
  GRAMMAR = 'GRAMMAR',
  VOCABULARY = 'VOCABULARY',
  CULTURAL = 'CULTURAL',
  OTHER = 'OTHER',
}

export enum MasteryLevel {
  NEW = 'NEW',
  LEARNING = 'LEARNING',
  KNOWN = 'KNOWN',
  MASTERED = 'MASTERED',
}

export enum DictionaryType {
  ALMANY = 'ALMANY',
  LIVING_ARABIC = 'LIVING_ARABIC',
  DERJA_NINJA = 'DERJA_NINJA',
  REVERSO = 'REVERSO',
  WIKTIONARY = 'WIKTIONARY',
  ARABIC_STUDENT_DICTIONARY = 'ARABIC_STUDENT_DICTIONARY',
  LANGENSCHEIDT = 'LANGENSCHEIDT',
  CUSTOM = 'CUSTOM',
}
