name: 'Backend Check'
description: 'Runs lint, test, and build for the backend'
outputs:
  status:
    description: 'The result of the backend check'
    value: ${{ steps.summary.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: â˜• Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: gradle

    - name: ðŸ”§ Grant execute permission for gradlew
      run: chmod +x ./backend/gradlew
      shell: bash

    - name: ðŸ“¦ Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: ðŸ” Run Gradle check
      working-directory: backend
      run: ./gradlew test detekt
      shell: bash

    - name: ðŸ³ Build Docker image
      working-directory: backend
      run: ./gradlew quarkusBuild
      shell: bash

    - name: ðŸ“Š Upload test results
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: backend-test-results
        path: backend/build/reports/tests/test/
        retention-days: 2

    - name: ðŸ“ Set output status
      id: summary
      if: always()
      run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
      shell: bash
