-- V2__Sample_Data.sql
-- Sample data for the An-Nahwi application

-- Sample texts
INSERT INTO texts (id, title, arabic_content, transliteration, translation, tags, difficulty, dialect, word_count, created_at, updated_at)
VALUES 
    ('17bd0e0e-9a5c-4d1a-8ac6-9f68bc5af56d',
     'مرحبا بالعالم', 
     'مرحبا بالعالم! كيف حالك اليوم؟', 
     'Marhaban bil-alam! Kayfa haluka al-yawm?', 
     'Hello world! How are you today?', 
     '["greeting", "beginner"]', 
     'BEGINNER', 
     'MSA', 
     6, 
     NOW(), 
     NOW()),
     
    ('c0316477-cdfb-4363-a0be-873856360272',
     'الطقس في تونس', 
     'الطقس جميل في تونس اليوم. الشمس مشرقة والسماء زرقاء.', 
     'At-taqs jamil fi tunis al-yawm. Ash-shams mushriqah wa as-sama zarqa.', 
     'The weather is beautiful in Tunisia today. The sun is shining and the sky is blue.', 
     '["weather", "tunisia", "intermediate"]', 
     'INTERMEDIATE', 
     'TUNISIAN', 
     12, 
     NOW(), 
     NOW()),
     
    ('e7640660-5640-4ab3-92b1-f6b93546bee7',
     'المأكولات المغربية', 
     'المأكولات المغربية متنوعة ولذيذة. الطاجين والكسكس من أشهر الأطباق المغربية.', 
     'Al-makulat al-maghribiyah mutanawiah wa ladhidhah. At-tajin wa al-kuskus min ashhar al-atbaq al-maghribiyah.', 
     'Moroccan food is diverse and delicious. Tagine and couscous are among the most famous Moroccan dishes.', 
     '["food", "morocco", "culture", "advanced"]', 
     'ADVANCED', 
     'MOROCCAN', 
     15, 
     NOW(), 
     NOW());

-- Sample words
INSERT INTO words (id, arabic, transliteration, translation, root, part_of_speech, notes, frequency, difficulty, dialect, is_verified, created_at)
VALUES 
    ('63bca32e-6f0a-4262-8fc5-f0582569add2',
     'مرحبا', 
     'marhaban', 
     'hello', 
     'ر-ح-ب', 
     'NOUN', 
     'Common greeting in Arabic', 
     10, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('df22bace-3d42-4731-b088-59acee2542bb',
     'عالم', 
     'alam', 
     'world', 
     'ع-ل-م', 
     'NOUN', 
     'Can also mean "universe" or "realm"', 
     8, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('383120e7-c3de-4a54-99a8-36db7178d43f',
     'كيف', 
     'kayfa', 
     'how', 
     NULL, 
     'PARTICLE', 
     'Interrogative particle', 
     15, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('e25ea207-dddc-4b7b-b72e-b059bd0a9a6a',
     'حال', 
     'hal', 
     'state, condition', 
     'ح-و-ل', 
     'NOUN', 
     'Often used in greetings', 
     12, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('708ea5dd-ddfa-48df-b15b-fdb291b87c72',
     'يوم', 
     'yawm', 
     'day', 
     'ي-و-م', 
     'NOUN', 
     'Plural: أيام (ayyam)', 
     20, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('e9ab9e43-8c7b-4641-bd1e-d24b39a42da2',
     'طقس', 
     'taqs', 
     'weather', 
     'ط-ق-س', 
     'NOUN', 
     'Related to climate and atmospheric conditions', 
     7, 
     'INTERMEDIATE', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('ee272022-1e85-4ee3-9707-1da1c023e3bb',
     'جميل', 
     'jamil', 
     'beautiful', 
     'ج-م-ل', 
     'ADJECTIVE', 
     'Feminine form: جميلة (jamilah)', 
     9, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('b1206831-59b2-46db-afc7-f736f8487607',
     'تونس', 
     'tunis', 
     'Tunisia', 
     NULL, 
     'NOUN', 
     'Country in North Africa', 
     5, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('39d834b6-bae6-476b-b783-3ea8d72078ae',
     'شمس', 
     'shams', 
     'sun', 
     'ش-م-س', 
     'NOUN', 
     'Feminine noun in Arabic', 
     8, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('a07c9a5c-380c-4c0a-93fb-57b8883c79cb',
     'سماء', 
     'sama', 
     'sky', 
     'س-م-و', 
     'NOUN', 
     'Plural: سماوات (samawat)', 
     6, 
     'BEGINNER', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('f1a99a91-59a5-4ff0-8ddf-5a99b4c0eb98',
     'مأكولات', 
     'makulat', 
     'food, cuisine', 
     'أ-ك-ل', 
     'NOUN', 
     'Plural of مأكول (makul)', 
     4, 
     'INTERMEDIATE', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('9cdc7651-2e8b-452f-abda-61dda2ad063b',
     'مغربية', 
     'maghribiyah', 
     'Moroccan (feminine)', 
     'غ-ر-ب', 
     'ADJECTIVE', 
     'Relating to Morocco', 
     3, 
     'INTERMEDIATE', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('0d41bfc8-d086-4033-99ff-c12d3fe32213',
     'متنوعة', 
     'mutanawiah', 
     'diverse, varied (feminine)', 
     'ن-و-ع', 
     'ADJECTIVE', 
     'Masculine form: متنوع (mutanawi)', 
     5, 
     'ADVANCED', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('ad07b387-52b0-4d99-b147-af4658826b9e',
     'لذيذة', 
     'ladhidhah', 
     'delicious (feminine)', 
     'ل-ذ-ذ', 
     'ADJECTIVE', 
     'Masculine form: لذيذ (ladhidh)', 
     7, 
     'INTERMEDIATE', 
     'MSA', 
     TRUE, 
     NOW()),
     
    ('f7a2be29-c74b-44ef-95a3-32e288864500',
     'طاجين', 
     'tajin', 
     'tagine', 
     NULL, 
     'NOUN', 
     'Traditional North African dish and the pot it is cooked in', 
     2, 
     'INTERMEDIATE', 
     'MOROCCAN', 
     TRUE, 
     NOW()),
     
    ('8d002f62-c744-41d2-b580-101a384ba44f',
     'كسكس', 
     'kuskus', 
     'couscous', 
     NULL, 
     'NOUN', 
     'Traditional North African dish made from semolina', 
     2, 
     'INTERMEDIATE', 
     'MOROCCAN', 
     TRUE, 
     NOW());


-- Sample annotations
INSERT INTO annotations (id, text_id, content, position_start, position_end, type, color, created_at)
VALUES 
    ('eb1a84d3-6faa-4c2d-a34a-7c33008e5970',
     '17bd0e0e-9a5c-4d1a-8ac6-9f68bc5af56d',
     'مرحبا is a common greeting in Arabic, equivalent to "hello" in English.', 
     0, 5, 
     'VOCABULARY', 
     '#4CAF50', 
     NOW()),
     
    ('faef2b15-3be1-4082-94c1-966c2d69d1b8',
     '17bd0e0e-9a5c-4d1a-8ac6-9f68bc5af56d',
     'كيف حالك is a common phrase asking "how are you" in Arabic.', 
     14, 22, 
     'VOCABULARY', 
     '#2196F3', 
     NOW()),
     
    ('7b100d82-2df2-4600-b06a-deac34666ade',
     'c0316477-cdfb-4363-a0be-873856360272',
     'In Arabic, adjectives typically follow the noun they modify, as in الطقس جميل (the weather is beautiful).', 
     0, 10, 
     'GRAMMAR', 
     '#FF9800', 
     NOW()),
     
    ('de693a71-3a7d-492d-9f88-891ebbb8ee8c',
     'c0316477-cdfb-4363-a0be-873856360272',
     'The word مشرقة (shining) is a feminine adjective that agrees with الشمس (the sun), which is feminine in Arabic.', 
     30, 35, 
     'GRAMMAR', 
     '#FF9800', 
     NOW()),
     
    ('dcae0686-ce57-44fd-b816-c50d558a6ceb',
     'e7640660-5640-4ab3-92b1-f6b93546bee7',
     'الطاجين (tagine) is a traditional North African dish named after the earthenware pot in which it is cooked.', 
     40, 47, 
     'CULTURAL', 
     '#9C27B0', 
     NOW()),
     
    ('d109958b-2962-4559-945e-fa3bcc3fa6fe',
     'e7640660-5640-4ab3-92b1-f6b93546bee7',
     'الكسكس (couscous) is a staple food in North African cuisine, made from semolina grains.', 
     48, 54, 
     'CULTURAL', 
     '#9C27B0', 
     NOW()),
     
    ('4e4501ac-c3da-4fec-aadd-4b2563388007',
     'e7640660-5640-4ab3-92b1-f6b93546bee7',
     'The phrase من أشهر means "among the most famous" and is commonly used to highlight important items in a category.', 
     55, 62, 
     'VOCABULARY', 
     '#4CAF50', 
     NOW());
