quarkus:
  # Development-specific configuration
  
  # Enable development mode
  dev:
    enabled: true
    
  # Live reload
  live-reload:
    enabled: true
    
  # More verbose logging in development
  log:
    console:
      level: DEBUG
    category:
      "com.tonihacks.annahwi":
        level: DEBUG
      "org.hibernate.SQL":
        level: DEBUG
        
  # Development-specific database settings
  datasource:
    jdbc:
      # Use a smaller connection pool in development
      max-size: 8
      
  # Show SQL formatted in development
  hibernate-orm:
    log:
      sql: true
      format-sql: true
      
  # Development-specific Swagger settings
  swagger-ui:
    always-include: true
    
  # Enable dev services (provides dev containers)
  devservices:
    enabled: true
    
  # Hot reload
  hot-reload:
    enabled: true
