quarkus:
  application:
    name: annahwi
  
  # HTTP configuration
  http:
    port: 8080
    cors:
      ~: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Content-Type,Authorization
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true
  
  # Database configuration
  datasource:
    db-kind: postgresql
    username: ${QUARKUS_DATASOURCE_USERNAME:annahwi_user}
    password: ${QUARKUS_DATASOURCE_PASSWORD:dev_password}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/annahwi}
      max-size: 16
  
  # Flyway configuration
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    locations: db/migration
    validate-on-migrate: true
  
  # Hibernate configuration
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  
  # Logging configuration
  log:
    console:
      enable: true
      level: INFO
    category:
      "com.tonihacks.annahwi":
        level: DEBUG
  
  # OpenAPI and Swagger UI
  swagger-ui:
    always-include: true
    path: /swagger-ui
  
  # Health checks
  smallrye-health:
    ui:
      always-include: true
  
  # Metrics
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /metrics
